<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="TestResults\**" />
    <EmbeddedResource Remove="TestResults\**" />
    <None Remove="TestResults\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <None Update="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UnityModBase\UnityModBase.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Unity.InputSystem">
      <HintPath>..\ReferenceLibrary\Unity.InputSystem.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\ReferenceLibrary\UnityEngine.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\ReferenceLibrary\UnityEngine.CoreModule.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>..\ReferenceLibrary\UnityEngine.IMGUIModule.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>..\ReferenceLibrary\UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

</Project>
